var instances = {
    'com.ericsson.oss.fa.flows.fillNodeData': [{

        "name": "Fill data for 100 nodes",
        "flowSource": "EXTERNAL",
        "flowId": "com.ericsson.oss.fa.flows.fillNodeData2",
        "flowName": "Fill the node data.",
        "startTime": 1487074493014,
        "state": "EXECUTING",
        "summaryReport": '',
        "endTime": 1487074593989,
        "duration": 53456,
        "executedBy": "User 2",
        "importedBy": "User 2",
        "flowVersion": "1.0.1",
        "processInstanceId": "12345678901"
    }, {

        "name": "Fill data for 1000 nodes",
        "flowSource": "EXTERNAL",
        "flowId": "com.ericsson.oss.fa.flows.fillNodeData",
        "flowName": "Fill the node data.",
        "state": "COMPLETED",
        "summaryReport": null,
        "endTime": 1487074593989,
        "duration": 79200000,
        "executedBy": "User 2",
        "importedBy": "User 2",
        "flowVersion": "1.0.1",
        "processInstanceId": "1234567890"
    }
    ],
    'com.ericsson.oss.fa.flows.autoSwRollout': [
        {
            "name": "instances app: flow instance to be stopped",
            "flowSource": "EXTERNAL",
            "flowId": "com.ericsson.oss.fa.flows.autoSwRollout",
            "flowName": "Auto SW Rollout",
            "flowVersion": "1.0.1",
            "createdBy": "User 1",
            "executedBy": "User 1",
            "startTime": 1539251342416,
            "endTime": null,
            "duration": null,
            "summaryReport": null,
            "state": "EXECUTING",
            "activeUserTasks": 0,
            "processInstanceId": "1234567890"
        },
        {
            "name": "1task",
            "flowId": "com.ericsson.oss.fa.flows.autoSwRollout",
            "flowSource": "EXTERNAL",
            "flowName": "Auto SW Rollout",
            "flowVersion": "1.0.1",
            "createdBy": "faadmin",
            "executedBy": "faadmin",
            "startTime": 1539251342416,
            "endTime": null,
            "duration": null,
            "summaryReport": null,
            "state": "SETTING_UP",
            "numberActiveUserTasks": 1,
            "processInstanceId": "1234567890"
        },
        {
            "name": "mock-more-user-tasks",
            "flowSource": "EXTERNAL",
            "flowId": "com.ericsson.oss.fa.flows.autoSwRollout",
            "flowName": "Auto SW Rollout",
            "flowVersion": "1.0.11",
            "createdBy": "faadmin",
            "executedBy": "faadmin",
            "startTime": 1539251249486,
            "endTime": null,
            "duration": null,
            "summaryReport": null,
            "state": "SETTING_UP",
            "numberActiveUserTasks": 1,
            "processInstanceId": "1234567890"
        },
        {
            "name": "mock-setup",
            "flowSource": "EXTERNAL",
            "flowId": "com.ericsson.oss.fa.flows.autoSwRollout",
            "flowName": "Flow with user task schema",
            "flowVersion": "1.0.11",
            "createdBy": "administrator",
            "executedBy": "administrator",
            "startTime": 1541086513491,
            "endTime": null,
            "duration": null,
            "summaryReport": null,
            "state": "SETTING_UP",
            "numberActiveUserTasks": 1,
            "processInstanceId": "1234567890"
        }],
    'com.ericsson.oss.fa.flows.collectPMCounters': [
        {
            "name": "0task",
            "flowSource": "EXTERNAL",
            "flowId": "com.ericsson.oss.fa.flows.collectPMCounters",
            "flowName": "Predefined Flow without Setup phase",
            "flowVersion": "1.0.1",
            "createdBy": "#Ericsson",
            "executedBy": "faadmin",
            "startTime": 1539251327903,
            "endTime": 1539251329109,
            "duration": 1206,
            "summaryReport": null,
            "state": "EXECUTING",
            "activeUserTasks": 0,
            "processInstanceId": "1234567890"
        },
        {
            "name": "0taski",
            "flowSource": "EXTERNAL",
            "flowId": "com.ericsson.oss.fa.flows.collectPMCounters",
            "flowName": "Predefined Flow without Setup phase",
            "flowVersion": "1.0.1",
            "createdBy": "#Ericsson",
            "executedBy": "faadmin",
            "startTime": 1539251334788,
            "endTime": 1539251334907,
            "duration": 119,
            "summaryReport": null,
            "state": "COMPLETED",
            "activeUserTasks": 0,
            "processInstanceId": "1234567890"
        }
    ],
    'com.ericsson.oss.fa.flows.errorHandling': [{
        "name": "setup-failed",
        "flowId": "com.ericsson.oss.fa.flows.errorHandling",
        "flowName": "Error Handling",
        "flowVersion": "1.0.1",
        "createdBy": "faadmin",
        "executedBy": "faadmin",
        "startTime": "2018-05-10 13:14:22",
        "endTime": "2018-05-10 13:18:29",
        "duration": "00:04:07",
        "state": "FAILED_SETUP",
        "numberActiveUserTasks": 0,
        "flowSource": "EXTERNAL",
        "summaryReport": "Setup Failed"
    }, {
        "name": "execute-failed",
        "flowId": "com.ericsson.oss.fa.flows.errorHandling",
        "flowName": "Error Handling",
        "flowVersion": "1.0.1",
        "createdBy": "faadmin",
        "executedBy": "faadmin",
        "startTime": "2018-05-10 13:14:40",
        "endTime": "2018-05-10 13:14:53",
        "duration": "00:00:13",
        "state": "FAILED_EXECUTE",
        "numberActiveUserTasks": 0,
        "flowSource": "EXTERNAL",
        "summaryReport": "Execute Failed"
    }],
    'com.ericsson.oss.fa.flows.autoSoftwareRollout': [{

        "name": "Fill data for 100 nodes-1",
        "flowSource": "EXTERNAL",
        'flowId': 'com.ericsson.oss.fa.flows.autoSoftwareRollout',
        "flowName": "Auto Software Rollout",
        "startTime": 1487074493014,
        "state": "EXECUTING",
        "summaryReport": null,
        "endTime": 1487074593989,
        "duration": 53456,
        "executedBy": "User 1",
        "importedBy": "User 1",
        "flowVersion": "1.0.1",
        "processInstanceId": "1234567899"
    }, {

        "name": "Fill data for 100 nodes-2",
        "flowSource": "EXTERNAL",
        "flowName": "Auto Software Rollout",
        'flowId': 'com.ericsson.oss.fa.flows.autoSoftwareRollout',
        "startTime": 1487074493014,
        "state": "STOPPED",
        "summaryReport": null,
        "endTime": 1487074593989,
        "duration": 53456,
        "executedBy": "User 1",
        "importedBy": "User 1",
        "flowVersion": "1.0.1",
        "processInstanceId": "1234567890"
    }, {
        "name": "Fill data for 100 nodes-3",
        "flowSource": "EXTERNAL",
        "flowName": "Auto Software Rollout",
        'flowId': 'com.ericsson.oss.fa.flows.autoSoftwareRollout',
        "startTime": 1487074493014,
        "state": "FAILED",
        "summaryReport": null,
        "endTime": 1487074593989,
        "duration": 53456,
        "executedBy": "User 1",
        "importedBy": "User 1",
        "flowVersion": "1.0.1",
        "processInstanceId": "1234567890"
    }],
    'com.ericsson.oss.fa.flows.usertaskShowcase.i18n': [{
        "name": "internationalization-tests",
        "flowId": "com.ericsson.oss.fa.flows.usertaskShowcase.i18n",
        "flowName": "Usertask Showcase with i18n",
        "flowVersion": "1.0.6",
        "createdBy": "faadmin",
        "executedBy": "faadmin",
        "startTime": "2019-08-07 09:45:39",
        "endTime": null,
        "duration": null,
        "state": "SETTING_UP",
        "numberActiveUserTasks": 1,
        "flowSource": "EXTERNAL",
        "summaryReport": null,
        "processInstanceId": "1d12c492-b8f8-11e9-bb9a-0242ac1d0005"
    }, {
        "name": "report-internationalization-tests",
        "flowId": "com.ericsson.oss.fa.flows.usertaskShowcase.i18n",
        "flowName": "Usertask Showcase with i18n",
        "flowVersion": "1.0.6",
        "createdBy": "faadmin",
        "executedBy": "faadmin",
        "startTime": "2019-08-07 09:45:39",
        "endTime": "2019-08-10 09:45:39",
        "duration": 1190,
        "state": "COMPLETED",
        "numberActiveUserTasks": 0,
        "flowSource": "EXTERNAL",
        "summaryReport": null,
        "processInstanceId": "1d12c492-b8f8-11e9-bb9a-0242ac1d0085"
    }]
};

module.exports = {
    instances: instances
};